# Generated by Django 4.1.3 on 2023-04-13 11:40

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=200)),
                ('duration', models.PositiveIntegerField(default=7)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('salad_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salad_name', models.CharField(max_length=100)),
                ('salad_price', models.PositiveIntegerField()),
                ('salad_desc', models.TextField()),
                ('salad_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='salad')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usermembership', to='store.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usermembership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expires_in', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('user_membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='store.usermembership')),
            ],
        ),
    ]
